/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ums;

import Lecterers.Lecterer_Login;
import Students.Student_Login;

/**
 *
 * @author sampath
 */
public class Home_page extends javax.swing.JFrame {

    /**
     * Creates new form Home_page
     */
    public Home_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Admin_Button1 = new javax.swing.JButton();
        Lecterer_Button1 = new javax.swing.JButton();
        Student_Button1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("University management system");
        setBackground(new java.awt.Color(0, 0, 0));

        Admin_Button1.setText("Admin Login");
        Admin_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_Button1ActionPerformed(evt);
            }
        });

        Lecterer_Button1.setText("Lecterer Login");
        Lecterer_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lecterer_Button1ActionPerformed(evt);
            }
        });

        Student_Button1.setText("Student Login");
        Student_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Student_Button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Student_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lecterer_Button1)
                    .addComponent(Admin_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Admin_Button1)
                .addGap(18, 18, 18)
                .addComponent(Lecterer_Button1)
                .addGap(18, 18, 18)
                .addComponent(Student_Button1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Admin_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_Button1ActionPerformed
        Admin_login admin = new Admin_login();
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Admin_Button1ActionPerformed

    private void Lecterer_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lecterer_Button1ActionPerformed
        Lecterer_Login lec = new Lecterer_Login();
        lec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Lecterer_Button1ActionPerformed

    private void Student_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Student_Button1ActionPerformed
        Student_Login student = new Student_Login();
        student.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Student_Button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin_Button1;
    private javax.swing.JButton Lecterer_Button1;
    private javax.swing.JButton Student_Button1;
    // End of variables declaration//GEN-END:variables
}
